
// src/app/layout.js
import localFont from "next/font/local";
import "./globals.css";
import Pokeshell from "./shell/Pokeshell";

const pokeFont = localFont({
  src: "./fonts/pokemon-b-w.otf.woff2",
  variable: "--font-poke",
});


export const metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={` ${pokeFont.variable} antialiased`}>
        <Pokeshell title="Pokédex">{children}</Pokeshell>
      </body>
    </html>
  );
}



<div className="bg-red-500 text-white p-4">Tailwind works</div>